site_name: Onegini Identity Cloud
site_description: Onegini public documentation

nav:
  - Introduction: index.md

extra:
  search:
    tokenizer: '[\s\-\.]+'
  manifest: 'manifest.webmanifest'
plugins:
  - search
  - redirects:
      redirect_maps:
