site_name: Onegini docs
site_description: Onegini public documentation

nav:

extra:
  search:
    tokenizer: '[\s\-\.]+'
  manifest: 'manifest.webmanifest'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
  - toc:
      permalink: true
plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'https://docs.onegini.com'
