site_name: Onegini Identity Cloud
site_description: Onegini public documentation
repo_url: https://github.com/Onegini/onegini-identity-cloud-documentation

nav:
  - 'Introduction': index.md
  - 'Architecture':
#      - Functional flows: lorem-ipsum/functional-flows.md
      - 'Mobile Identity & Access': architecture/mobile-identity-access.md
#  - Identity management:
#    - Identity management: lorem-ipsum/identity-management.md
#    - Identity Proofing: lorem-ipsum/identity-proofing.md
  - 'Third party identity providers': identity-providers.md
#  - 'Strong (multi-factor) authentication': lorem-ipsum/strong-authentication.md
  - 'Single sign-on (SSO)':
#      - Action tokens: lorem-ipsum/action-tokens.md
#      - OpenID Connect: lorem-ipsum/openid-connect.md
      - 'Protected data in Single Page Apps': single-sign-on/protected-data-openid-connect-access-tokens.md
#      - SAML: lorem-ipsum/saml.md
#      - Sign out: lorem-ipsum/single-sign-out.md
#      - Web applications: lorem-ipsum/sign-in-web.md
#  - Device registration and management: lorem-ipsum/device-registration.md
#  - Secure mobile apps: lorem-ipsum/secure-mobile-apps.md
  - 'Client environment embedding (implementation)':
      - 'OAuth vs OpenID Connect': oauth-vs-oidc.md
      - 'Responsibilities of external system connected to DABP': dabp/guides/external-systems-responsibilities.md
#    - 'Feature lifecycle management': lorem-ipsum/feature-lifecycle-management.md
  - 'Delegated administration': dabp/index.md
      - 'In-depth view on permissions': dabp/guides/permissions-in-depth.md
      - 'In-depth view on policies': dabp/guides/policies-in-depth.md
      - 'Inviting users in DABP': dabp/guides/inviting-users.md
      - 'Managing subgroups best practices': dabp/guides/subgroups-best-practices.md
      - 'How and when to use custom attributes on groups': dabp/guides/group-attributes.md
      - 'How to create a new policy via the API': dabp/guides/create-policy-via-api.md
      - 'Person report - What is it and how to generate it': dabp/guides/person-report.md
#  - 'Monitoring, logging & alerting': lorem-ipsum/monitoring.md
#  - API descriptions: lorem-ipsum/api-descriptions.md
copyright: "Onegini B.V."

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
  - javascripts/reading-time.js
  - javascripts/mermaid-config.js
  - javascripts/mermaid-custom-loader.js

theme:
  name: 'material'
  logo: 'images/onegini-logo-white.svg'
  favicon: 'images/favicon.ico'
  font: false
  custom_dir: 'theme'

extra:
  search:
    tokenizer: '[\s\-\.]+'
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Onegini
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/onegini/
    - icon: fontawesome/brands/vimeo
      link: https://vimeo.com/onegini

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - redirects:
      redirect_maps:
