site_name: Onegini Identity Cloud for Developers
site_description: 'Documentation of the Onegini Identity Cloud: architecture, concepts, functional descriptions and the APIs explained.'
repo_url: https://github.com/Onegini/onegini-identity-cloud-documentation

nav:
  - 'Introduction': index.md
  - 'Onegini Identity Cloud':
    - 'Platform architecture':
        - 'Mobile Identity & Access': architecture/mobile-identity-access.md
        - 'Identity & Single Sign-On': architecture/identity-single-sign-on.md
  - 'Topic guides':
    - 'Third party identity providers': identity-providers.md
    - 'Single sign-on (SSO)':
        - 'Protected data in Single Page Apps': single-sign-on/protected-data-openid-connect-access-tokens.md
    - 'Client environment embedding (implementation)':
        - 'OAuth vs OpenID Connect': oauth-vs-oidc.md
        - 'Responsibilities of external system connected to DABP': dabp/guides/external-systems-responsibilities.md
  - 'Products':
    - 'Customer Service': products/customer-service.md
    - 'Delegated administration':
        - 'Introduction': dabp/index.md
        - 'Concepts':
          - 'In-depth view on permissions': dabp/guides/permissions-in-depth.md
          - 'In-depth view on policies': dabp/guides/policies-in-depth.md
        - 'How to functional':
          - 'Inviting users in DABP': dabp/guides/inviting-users.md
          - 'Managing subgroups best practices': dabp/guides/subgroups-best-practices.md
          - 'How and when to use custom attributes on groups': dabp/guides/group-attributes.md
        - 'How to technical':
          - 'How to create a new policy via the API': dabp/guides/create-policy-via-api.md
          - 'Person report - What is it and how to generate it': dabp/guides/person-report.md
    - 'Identity & Single Sign-On': products/identity-single-sign-on.md
    - 'Mobile Identity & Access': products/mobile-identity-access.md
copyright: "Onegini B.V."

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
  - javascripts/reading-time.js
  - javascripts/mermaid-config.js
  - javascripts/mermaid-custom-loader.js

theme:
  name: 'material'
  logo: 'images/onegini-logo-white.svg'
  favicon: 'images/favicon.ico'
  font: false
  custom_dir: 'theme'

extra:
  search:
    tokenizer: '[\s\-\.]+'
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Onegini
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/onegini/
    - icon: fontawesome/brands/vimeo
      link: https://vimeo.com/onegini

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - redirects:
      redirect_maps:
