version: 2.1
orbs:
    onegini-build: onegini/onegini-build@3

workflows:
  version: 2
  build-workflow:
    jobs:
      - onegini-build/build-docs:
        executor:
          name: onegini-build/docs-builder
          # Keep in line with readthedocs.yml python version
          tag: "3.7-browsers"
